name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main  # Customize this branch name to match your repository's main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build Hugo site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Path to the Hugo generated HTML files
        publish_branch: gh-pages  # Branch where the site will be deployed
        # publish_repo: ${{ github.repository }}  # Repository to deploy to
        enable_jekyll: false  # Disable Jekyll processing for Hugo

